# -*- mode: indented-text; tab-width: 3; indent-tabs-mode: nil -*-

version: '3'

services:

  reverse-proxy-to-cs:
     restart: unless-stopped
     hostname: reverse-proxy-to-peugeotbox

     ports:
        - "8890:80"

     environment:
        CREDENTIAL_FILE: /etc/pcrproxy/SECRETs/peugeotbox_credential.txt

     networks:
        - auto_https_reverse_proxy
        - internal_services

networks:
   auto_https_reverse_proxy:
      external: true
      name: revproxy

   internal_services:
      external: true
      name: internal_services
