# -*- mode: indented-text; tab-width: 3; indent-tabs-mode: nil -*-

version: '3'

services:

  reverse-proxy-to-cs:
     image: pcrproxy
     restart: unless-stopped
     environment:
        - STAT_DATA_DIR="/var/pc_stats"
     volumes:
        - ./my-httpd.conf:/usr/local/apache2/conf/httpd.conf
        - ./filter/:/filter/
        - ./pc_stats/:/var/pc_stats/
