# -*- mode: indented-text; tab-width: 3; indent-tabs-mode: nil -*-

version: '3'

services:

  reverse-proxy-to-cs:
     build: .
     image: pcrproxy:latest
     environment:
        - STAT_DATA_DIR=/var/pc_stats
        - TZ=Europe/Paris
        - CREDENTIAL_FILE=/etc/pcrproxy/SECRETs/cs_credential.txt
        - FILTER_DEBUG=yes

     volumes:
        - ./my-httpd.conf:/usr/local/apache2/conf/httpd.conf
        - ./filter/:/filter/
        - ./pc_stats/:/var/pc_stats/
        - RPROXY_CONFIG:/etc/pcrproxy/

volumes:

   NEXTCLOUD_EXTERNAL_STORAGE1:
      external:
         name: VOL4NEXTCLOUD_EXTERNAL_STORAGE

   RPROXY_CONFIG:
      external:
         name: VOL4NEXTCLOUD_RPROXY_CONFIG
