# -*- mode: indented-text; tab-width: 3; indent-tabs-mode: nil -*-

version: '3'

services:

  reverse-proxy-to-cs:
     restart: unless-stopped
     ports:
        - 7777:80
     environment:
        - VIRTUAL_HOST=cs.pctest.freeddns.org
        - VIRTUAL_PORT=7777
        - LETSENCRYPT_HOST=cs.pctest.freeddns.org
        - LETSENCRYPT_EMAIL=raphael.bernhard@orange.fr
     networks:
        - auto_https_reverse_proxy

networks:
  auto_https_reverse_proxy:
     external:
        name: webservices
