# -*- mode: indented-text; tab-width: 3; indent-tabs-mode: nil -*-

version: '3'

x-reverse-proxy-common: &reverse-proxy-common
  build: .
  image: pcrproxy:latest
  expose:
     - "80"

x-shared_volumes:
  volumes: &shared_volumes
  - ./filter/:/filter/
  - ./pc_stats/:/var/pc_stats/
  - RPROXY_CONFIG:/etc/pcrproxy/

x-shared_environment:
  environment: &shared_environment
     STAT_DATA_DIR: /var/pc_stats
     TZ: Europe/Paris
     FILTER_DEBUG: file

services:

  reverse-proxy-peugeotbox:
     <<: *reverse-proxy-common
#     profiles: ["peugeotbox"]
     restart: unless-stopped
     hostname: reverse-proxy-to-peugeotbox
     ports:
        - "8890:80"
     environment:
        <<: *shared_environment
        CREDENTIAL_FILE: /etc/pcrproxy/SECRETs/peugeotbox_credential.txt
     volumes:
#????     <<: *shared_volumes
     - ./peugeotbox-httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
     networks:
        - auto_https_reverse_proxy
        - internal_services

networks:
   default:
   
   auto_https_reverse_proxy:
      external: true
      name: revproxy

   internal_services:
      external: true
      name: internal_services

volumes:

   NEXTCLOUD_EXTERNAL_STORAGE1:
      external: true
      name: VOL4NEXTCLOUD_EXTERNAL_STORAGE

   RPROXY_CONFIG:
      external: true
      name: VOL4NEXTCLOUD_RPROXY_CONFIG
