# -*- mode: indented-text; tab-width: 3; indent-tabs-mode: nil -*-

version: '3'

services:

  reverse-proxy-to-cs:
     ports:
        - 7778:80
     volumes:
        - ./my-httpd.conf:/usr/local/apache2/conf/httpd.conf
