# -*- mode: indented-text; tab-width: 3; indent-tabs-mode: nil -*-

version: '3'

services:

  reverse-proxy-to-cs-plus:
     restart: unless-stopped
     ports:
        - 8889:80
     environment:
        - VIRTUAL_HOST=csdepc-plus.forumtestplanetecitroen.fr
        - LETSENCRYPT_HOST=csdepc-plus.forumtestplanetecitroen.fr
        - VIRTUAL_PORT=8889
     networks:
        - auto_https_reverse_proxy
        - internal_services

networks:
   auto_https_reverse_proxy:
      external:
         name: revproxy

   internal_services:
      external:
         name: internal_services
