# -*- mode: indented-text; tab-width: 3; indent-tabs-mode: nil -*-

version: '3'

services:

  reverse-proxy-to-cs:
     restart: unless-stopped
     hostname: reverse-proxy-to-cs-basic
     ports:
        - 8888:80
     environment:
        FILTER_DEBUG: file
     volumes:
        - ./my-httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
     networks:
        - auto_https_reverse_proxy
        - internal_services

networks:
   auto_https_reverse_proxy:
      external:
         name: revproxy

   internal_services:
      external:
         name: internal_services
