# -*- mode: indented-text; tab-width: 3; indent-tabs-mode: nil -*-

version: '3'

services:

  reverse-proxy-to-cs:
     image: pcrproxy
     restart: unless-stopped
     volumes:
        - ./my-httpd.conf:/usr/local/apache2/conf/httpd.conf
        - ./filter/:/filter/
