# -*- mode: indented-text; tab-width: 3; indent-tabs-mode: nil -*-

version: '3'

services:

  reverse-proxy-to-cs:
     restart: unless-stopped
     hostname: reverse-proxy-to-cs-plus
     ports:
        - 8889:80
     environment:
        - FILTER_DEBUG=file
     volumes:
        - ./my-httpd.conf:/usr/local/apache2/conf/httpd.conf
     networks:
        - auto_https_reverse_proxy
        - internal_services

networks:
   auto_https_reverse_proxy:
      external: true
      name: revproxy

   internal_services:
      external: true
      name: internal_services
