# -*- mode: indented-text; tab-width: 3; indent-tabs-mode: nil -*-

version: '3'

services:

  reverse-proxy-to-cs:
     restart: unless-stopped
     ports:
        - 8889:80
     environment:
        - CREDENTIAL_FILE=/etc/pcrproxy/SECRETs/cs_credential-plus.txt
        - FILTER_DEBUG=file
     networks:
        - auto_https_reverse_proxy
        - internal_services

networks:
   auto_https_reverse_proxy:
      external: true
      name: revproxy

   internal_services:
      external: true
      name: internal_services
