# -*- mode: indented-text; tab-width: 3; indent-tabs-mode: nil -*-

version: '3'

services:

  reverse-proxy-to-cs:
     build: .
     image: pcrproxy:latest

     expose:
        - 80

     environment:
        STAT_DATA_DIR: /var/pc_stats
        TZ: Europe/Paris
        FILTER_DEBUG: file
        DEBUG_ROOT_DIR: /var/pc_debug

     volumes:
        - ./cs2pc-rproxy-httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
        - ./filter/:/filter/:ro
        - ./pc_stats/:/var/pc_stats/
        - RPROXY_CONFIG:/etc/pcrproxy/:ro

volumes:

   NEXTCLOUD_EXTERNAL_STORAGE1:
      external: true
      name: VOL4NEXTCLOUD_EXTERNAL_STORAGE

   RPROXY_CONFIG:
      external: true
      name: VOL4NEXTCLOUD_RPROXY_CONFIG
