# -*- mode: indented-text; tab-width: 3; indent-tabs-mode: nil -*-

version: '3'

services:

  reverse-proxy-to-cs:
     restart: unless-stopped
     ports:
        - 8888:80
     environment:
        - VIRTUAL_HOST=csdepc.planete-citroen.com
        - VIRTUAL_PORT=8888
        - LETSENCRYPT_HOST=csdepc.planete-citroen.com
        - LETSENCRYPT_EMAIL=raphael.bernhard@orange.fr
     networks:
        - auto_https_reverse_proxy

networks:
  auto_https_reverse_proxy:
     external:
        name: webservices
