#! /bin/bash

# -*- mode: shell-script -*-

set -e

exec 2>/var/pc_debug/"$( basename "$0" )".log

(
    echo '==============================='
    date
    echo
    env
) 1>&2

#!!!set -x

HERE=$( dirname "$0" )

if [[ -r "${0}.env.secret" ]]
then
    source "${0}.env.secret"
fi

urlencode() {
    # urlencode <string>

    old_lc_collate=$LC_COLLATE
    LC_COLLATE=C

    local length="${#1}"
    for (( i = 0; i < length; i++ )); do
        local c="${1:$i:1}"
        case $c in
            [a-zA-Z0-9.~_-])
		printf '%s' "$c"
		;;
            *)
		printf '%%%02X' "'$c"
		;;
        esac
    done

    LC_COLLATE=$old_lc_collate
}

html_log_message () {
    echo "$@" | while read -r line
    do
       echo "<p>=== ${line} </p>"
    done
}

query_string_array_init_val=$(

    IFS='&'
    set -- ${QUERY_STRING}
    for i in "$@"
    do
       IFS='='
       set -- $i
       echo "[$1]=$2"
    done

)
eval declare -A query_string_array=( ${query_string_array_init_val} )

#
# get SAML Auth
#

# get JSESSIONID PSACOUNTRY & BIGIPSERVER cookies

_old_IFS="${IFS}"
IFS=';, ';
for i in ${HTTP_COOKIE}
do
    case "${i}" in
	JSESSIONID\=* )
	    SET_JSESSIONID="${i}"
	    ;;
	PSACountry\=* )
	    SET_PSA_COUNTRY="${i}"
	    ;;

	 BIGipServer* )
	    SET_BIGIPSERVER="${i}"
	    ;;

	* )
	    ;;
    esac
done
IFS="${_old_IFS}"

: ${PUBLIC_SERVICE_BOX_ROOT_URL:='https://public.servicebox-parts.com/'}

USERAGENT='Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0'

test_HTTP_REQ='HTTP/1.1 200 
Cache-control: no-cache, no-store, max-age=0
Pragma: no-cache
SAMLRequest: jZJPT+MwFMTvfArr3R3nH7S1mqLuogoEiIike9jLynGc1trEDn5OBd+ebEq1HBBwfjOa8fy8vHzuWnJQDrU1GURBCEQZaWttdhlsyw2dw+XqbImia/uYrwe/N4/qaVDoyeg0yI+XDAZnuBWokRvRKeRe8mJ9f8fjIOS9s95K2wJZIyrnx6yf1uDQKVcod9BSbR/vMth73yNnrB+qVssAj6fKPtNeOI+BtB3b6d2LKIoHIFdjB22En4qfrI2uu0ANUTDpJse/guww1mDpH+s23fb2OiqdycO/902ydy9uzXTdM0QLZGOdVNMjM2hEiwrIzVUGYRLOZKUSWs+SmKaL5pxW9UVI42ZRJ3IuosW8GpWYC0R9UP+9iIO6MeiF8RnEYZzSKKJRWEbnPF3wNA2SePYbSP62zw9tjsN/NmZ1FCG/Lsuc5g9FCeTXCeAogDdcMZ/i3TtOX2ASJziw+g6KcbEle580BrMPPsrqFQ==
SAMLLogoutRequest: hZFBb8IwDIXv%2BxVV7mmaUto1oiAkhIYG0rTBDrtMaRpKtDbp4rSCf78AQ%2BIwaVfbz8%2Fv82R2bJtgkBaU0QWiYYQCqYWplK4LtNsu8SOaTR8mwNumi9na1KZ3r%2FK7l%2BACL9XArq0C9VYzw0EB07yVwJxgb%2FPNmsVhxDprnBGmQcHCC5Xm7mJ3cK4DRsheVW0oexrWqj7xUJiWnLeSwWtJ8mnsst09P9Gt1S%2FR12Y%2FOtiTnRNVdQQag4LVokBZmmdjLiTmeSpxIiqJyyopcU5TybOSUyFSPwkvHEANskB73oA8V6CXKw2Oa1egOIoTTCmm0ZaOWZKzJAlHcfaBgvcbIn8S%2BgUSs4va3oH4h4M3l%2FacHU1v2bu%2BbJQIfX1QQpbmiDtuHVwhgJmQeydvTP56xfQH
gigyaUrl: https://fidm.eu1.gigya.com/saml/v2.0/4_orFmUKH1TrnP0kMf3hryrA/idp/sso
Content-Length: 0
Date: Sun, 10 Nov 2024 14:49:43 GMT

'
HTTP_REQ="${test_HTTP_REQ}"

if [[ -z "${HTTP_REQ}" ]]
then

    HTTP_REQ=$(curl \
		    -s \
		    -D - \
		    -A "${USERAGENT}" \
		    -X POST \
		    --cookie "${SET_BIGIPSERVER}" \
		    --cookie "${SET_PSA_COUNTRY}" \
 		    --cookie "${SET_JSESSIONID}" \
 		    -d '' \
 		    "${PUBLIC_SERVICE_BOX_ROOT_URL}/getSamlReq"
	     )
fi

echo "==> HTTP_REQ: ${HTTP_REQ}" 1>&2
echo "${HTTP_REQ}" > /var/pc_debug/HTTP_REQ_getSamlReq.txt

while IFS= read -r header
do
        if [[ $header == *"gigyaUrl"* ]]; then
                GIGYAURL=$(echo -n $header | sed 's/^gigyaUrl: \(.*\)\r/\1/i')
                APIKEY=$(echo $header | sed 's/.*v2.0\/\([a-zA-Z0-9\-_]*\)\/.*$/\1/i')
        fi
        if [[ $header == *"SAMLRequest"* ]]; then
                SAMLREQUEST=$(echo -n $header | sed 's/^SAMLRequest: \(.*\)\r/\1/i')
                SAMLREQUEST_ENCODED=$(urlencode $SAMLREQUEST)
        fi
done <<< "$HTTP_REQ"

(
    echo "GIGYAURL"
    echo "==> $GIGYAURL"

    echo "APIKEY"
    echo $APIKEY

    echo "SAMLREQUEST"
    echo "${SAMLREQUEST}"
) 1>&2

GIGYAURL=$( echo "${HTTP_REQ}" | sed -n -e '/^gigya[uU]rl:/s/^gigya[uU]rl:[ \t]*\(.*\)$/\1/p' )
APIKEY=$( echo "${GIGYAURL}" | sed -n -e 's|.*/v2.0/\([^/]*\)/.*$|\1|p' )

SAMLREQUEST=$( echo "${HTTP_REQ}" | sed -n -e '/^SAMLRequest:/s/^SAMLRequest:[ \t]*\(.*\)$/\1/p' )
SAMLREQUEST_ENCODED=$( urlencode "${SAMLREQUEST}" )

(
    echo "GIGYAURL"
    echo "==> $GIGYAURL"

    echo "APIKEY"
    echo $APIKEY

    echo "SAMLREQUEST"
    echo "${SAMLREQUEST}"
) 1>&2


#
# call GIGYAURL
# =============
#


test_HTTP_REQ='HTTP/2 302 
content-length: 0
date: Sun, 10 Nov 2024 15:28:21 GMT
cache-control: private
location: https://www.technicalinformation.fiat.com/proxyPage.html?mode=login&samlContext=eu1_352063790294_08cd7025-da4a-497e-bc45-87acfb606d85&spName=POISP
p3p: CP="IDC COR PSA DEV ADM OUR IND ONL"
x-error-code: 0
x-soa: true, Gator
x-server: eu1a-nomad-t3
x-callid: 0f03ecb7b0754446b76525c612e21298
x-robots-tag: none

'

HTTP_REQ="${test_HTTP_REQ}"

: ${HTTP_REQ:=$(
    curl \
	-s \
	-D - \
	-A "${USERAGENT}" \
	-X GET "${GIGYAURL}"'?SAMLRequest='"${SAMLREQUEST_ENCODED}"
	)}

echo "${HTTP_REQ}" > /var/pc_debug/HTTP_REQ_GIGYAURL.txt

while IFS= read -r header
do
        if [[ $header == *"samlContext="* ]]; then
                SAMLCONTEXT=$(echo -n $header | sed 's/.*samlContext=\([^&]*\).*/\1/i')
        fi
done <<< "$HTTP_REQ"

(
    echo "SAMLCONTEXT"
    echo "==> $SAMLCONTEXT"

) 1>&2

SAMLCONTEXT=$( echo "${HTTP_REQ}" | sed -n -e '/&samlContext=/s/.*&samlContext=\([^&]*\).*/\1/p' )

(
    echo "SAMLCONTEXT"
    echo "==> $SAMLCONTEXT"

) 1>&2

#
# call https://login-ra.fiat.com/accounts.webSdkBootstrap
# =======================================================
#

test_HTTP_REQ='HTTP/2 200 
content-type: text/javascript; charset=utf-8
content-length: 199
date: Sun, 10 Nov 2024 15:50:38 GMT
cache-control: private
set-cookie: gmid=gmid.ver4.AtLtgOTaHQ.pJoMsCtK7BCeu9DnWD3YMG54Ifu1HGnhQbYLqaGEI-xHyTQawKl-qh2eQMc0Bg0F.fLROyC1GmEzb0p6Vz29jcalswwRCiJP61LjD8M89ZdlexmVSZU8E9pA9qRE3FExIYU5hG8MIaanHQHr5Vr9ikQ.sc3; expires=Mon, 10 Nov 2025 15:50:39 GMT; domain=.login-ra.fiat.com; path=/; secure; samesite=none; httponly
set-cookie: ucid=FgooeUBaDUjpPGWIPTo1-g; expires=Mon, 10 Nov 2025 15:50:39 GMT; domain=.login-ra.fiat.com; path=/; secure; samesite=none; httponly
set-cookie: hasGmid=ver4; expires=Sat, 10 May 2025 15:50:39 GMT; domain=.login-ra.fiat.com; path=/; secure; samesite=none
p3p: CP="IDC COR PSA DEV ADM OUR IND ONL"
x-error-code: 0
x-soa: true, Gator
x-server: eu1b-nomad-t7
x-callid: 8f7d6e656cda48199d5a1701cf61132d
x-robots-tag: none
x-cache: Miss from cloudfront
via: 1.1 5cf26f8164e0cad37f6634ff6aeac4ce.cloudfront.net (CloudFront)
x-amz-cf-pop: FRA60-P5
x-amz-cf-id: 78A3H2gltQxEGemmu0dbfe0vS0b1Hmje9eP7JC7tfIQdb3n7nBYPkQ==

{
  "callId": "8f7d6e656cda48199d5a1701cf61132d",
  "errorCode": 0,
  "apiVersion": 2,
  "statusCode": 200,
  "statusReason": "OK",
  "time": "2024-11-10T15:50:39.292Z",
  "hasGmid": "ver4"
}
'

HTTP_REQ="${test_HTTP_REQ}"

: ${HTTP_REQ:=$(
    curl \
	-s \
	-D - \
	-A "${USERAGENT}" \
	-X GET 'https://login-ra.fiat.com/accounts.webSdkBootstrap?apiKey='"${APIKEY}"'&pageURL='"${GIGYAURL}"'?SAMLRequest='"${SAMLREQUEST}"'&sdk=js_latest&sdkBuild=16506&format=json'
	)}

echo "${HTTP_REQ}" > /var/pc_debug/HTTP_REQ_webSdkBootstrap.txt

while IFS= read -r header
do
        if [[ $header == *"gmid="* ]]; then
                GMID=$(echo $header | sed 's/^Set-Cookie: \([^;]*;\).*$/\1/i')
        fi
        if [[ $header == *"ucid="* ]]; then
                UCID=$(echo $header | sed 's/^Set-Cookie: \([^;]*;\).*$/\1/i')
        fi
        if [[ $header == *"hasGmid="* ]]; then
                HASGMID=$(echo $header | sed 's/^Set-Cookie: \([^;]*;\).*$/\1/i')
        fi
done <<< "$HTTP_REQ"

(
    echo "GMID"
    echo "==> $GMID"

    echo "UCID"
    echo "==> $UCID"

    echo "HASGMID"
    echo "==> $HASGMID"

) 1>&2

GMID=$(echo "${HTTP_REQ}" | sed -n -e '/^[sS]et-[cC]ookie:.*gmid=/s/.et-.ookie:[ \t]*\([^;]*;\).*$/\1/p')
UCID=$(echo "${HTTP_REQ}" | sed -n -e '/^[sS]et-[cC]ookie:.*ucid=/s/.et-.ookie:[ \t]*\([^;]*;\).*$/\1/p')
HASGMID=$(echo "${HTTP_REQ}" | sed -n -e '/^[sS]et-[cC]ookie:.*hasGmid=/s/.et-.ookie:[ \t]*\([^;]*;\).*$/\1/p')

(
    echo "GMID"
    echo "==> $GMID"

    echo "UCID"
    echo "==> $UCID"

    echo "HASGMID"
    echo "==> $HASGMID"

) 1>&2

#
# call https://login-ra.fiat.com/accounts.webSdkBootstrap
# =======================================================
#

RISKCONTEXT=$( urlencode "{\"b0\":53295,\"b1\":[104,68,180,220],\"b2\":6,\"b3\":[],\"b4\":6,\"b5\":1,\"b6\":\"${USERAGENT}\",\"b7\":[],\"b8\":\"${TIME}:00\",\"b9\":-120,\"b10\":{\"state\":\"prompt\"},\"b11\":false,\"b12\":{\"charging\":true,\"chargingTime\":0,\"dischargingTime\":null,\"level\":1},\"b13\":[null,\"1024|728|24\",false,true]}" )

HTTP_REQ=$(
    curl \
	-s \
	-D - \
	-A "${USERAGENT}" \
	-X POST \
	-d "loginID=${LOGIN}" \
	-d "password=${PASSWORD}" \
	-d "sessionExpiration=2628000" \
	-d "targetEnv=jssdk" \
	-d "include=profile%2Cdata%2Cemails%2Csubscriptions%2Cpreferences%2C" \
	-d "includeUserInfo=true" \
	-d "loginMode=standard" \
	-d "lang=fr" \
	-d "riskContext=${RISKCONTEXT}" \
	-d "APIKey=${APIKEY}" \
	-d "source=showScreenSet" \
	-d "sdk=js_latest" \
	-d "authMode=cookie" \
	-d "pageURL=https%3A%2F%2Flogin-ra.fiat.com%2F" \
	-d "sdkBuild=16506" \
	-d "format=json" \
	--cookie "${GMID}" \
	--cookie "${UCID}" \
	--cookie "${HASGMID}" \
	'https://login-ra.fiat.com/accounts.login'
	)

echo "${HTTP_REQ}" > /var/pc_debug/HTTP_REQ_accounts_login.txt

while IFS= read -r header
do
        if [[ $header == *"glt_"* ]]; then
                GLT=$(echo $header | sed 's/^Set-Cookie: \([^;]*;\).*$/\1/i')
                LOGIN_TOKEN=$(echo $header | sed 's/^Set-Cookie: [^=]*=\([^;]*\);.*$/\1/i')
        fi
done <<< "$HTTP_REQ"

(
    echo "GLT"
    echo "==> $GLT"

    echo "LOGIN_TOKEN"
    echo "==> $LOGIN_TOKEN"

) 1>&2

GLT=$(echo "${HTTP_REQ}" | sed -n -e '/^[sS]et-[cC]ookie:.*glt_/s/.et-.ookie:[ \t]*\([^;]*;\).*$/\1/p')
LOGIN_TOKEN=$(echo "${HTTP_REQ}" | sed -n -e '/^[sS]et-[cC]ookie:.*glt_/s/.et-.ookie:[ \t]*\([^;]*;\).*$/\1/p')

(
    echo "GLT"
    echo "==> $GLT"

    echo "LOGIN_TOKEN"
    echo "==> $LOGIN_TOKEN"

) 1>&2

if [[ $LOGIN_TOKEN == "" ]]; then
        echo "Login ERROR"
        exit 1
fi


exit 1

echo 'Content-type: text/html'
echo 'RespHead: ABC'
echo "Set-Cookie: eee=1"
echo
echo '<html>
<head>
<title>HELLO cgi</title>
</head>'

html_log_message "$( date )"
html_log_message '==================================='
html_log_message "$(env)"
html_log_message "Query string array: ${query_string_array[@]}"
html_log_message "${HTTP_COOKIE}"

cat /tmp/zz.log

echo '</span>
</span>
</p>

</body>
</html>
'



exit 0



# IMPORTED OCDE



LOGIN=""
PASSWORD=""
TIME=$(date +"%H:%M")
USERAGENT="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0"

LOGIN_TOKEN=""

HTTP_REQ=$(curl -s -D - -A "${USERAGENT}" -X GET "https://public.servicebox-parts.com/")
while IFS= read -r header
do
    if [[ $header == "Set-Cookie: JSESSIONID"* ]]; then
                JSESSIONID=$(echo $header | sed 's/^Set-Cookie: \([^;]*;\).*$/\1
/i')
        fi
        if [[ $header == "Set-Cookie: BIGipServer"* ]]; then
                BIGIPSERVER=$(echo $header | sed 's/^Set-Cookie: \([^;]*;\).*$/\
1/i')
        fi
        if [[ $header == "Set-Cookie: PSACountry"* ]]; then
                PSACOUNTRY=$(echo $header | sed 's/^Set-Cookie: \([^;]*;\).*$/\1
/i')
        fi
done <<< "$HTTP_REQ"

HTTP_REQ=$(curl -s -D - -A "${USERAGENT}" -X POST "https://public.servicebox-parts.com/getSamlReq" -H "Cookie: ${JSESSIONID} ${PSACOUNTRY} ${BIGIPSERVER} " -d "")
while IFS= read -r header
do
        if [[ $header == *"gigyaUrl"* ]]; then
                GIGYAURL=$(echo -n $header | sed 's/^gigyaUrl: \(.*\)\r/\1/i')
                APIKEY=$(echo $header | sed 's/.*v2.0\/\([a-zA-Z0-9\-_]*\)\/.*$/\1/i')
        fi
        if [[ $header == *"SAMLRequest"* ]]; then
                SAMLREQUEST=$(echo -n $header | sed 's/^SAMLRequest: \(.*\)\r/\1/i')
                SAMLREQUEST_ENCODED=$(urlencode $SAMLREQUEST)
        fi
done <<< "$HTTP_REQ"

HTTP_REQ=$(curl -s -D - -A "${USERAGENT}" -X GET "${GIGYAURL}?SAMLRequest=${SAMLREQUEST_ENCODED}")
while IFS= read -r header
do
        if [[ $header == *"samlContext="* ]]; then
                SAMLCONTEXT=$(echo -n $header | sed 's/.*samlContext=\([^&]*\).*/\1/i')
        fi
done <<< "$HTTP_REQ"

#---------------------------

HTTP_REQ=$(curl -s -D - -A "${USERAGENT}" -X GET "https://login-ra.fiat.com/accounts.webSdkBootstrap?apiKey=${APIKEY}&pageURL=${GIGYAURL}?SAMLRequest=${SAMLREQUEST}&sdk=js_latest&sdkBuild=16506&format=json")
while IFS= read -r header
do
        if [[ $header == *"gmid="* ]]; then
                GMID=$(echo $header | sed 's/^Set-Cookie: \([^;]*;\).*$/\1/i')
        fi
        if [[ $header == *"ucid="* ]]; then
                UCID=$(echo $header | sed 's/^Set-Cookie: \([^;]*;\).*$/\1/i')
        fi
        if [[ $header == *"hasGmid="* ]]; then
                HASGMID=$(echo $header | sed 's/^Set-Cookie: \([^;]*;\).*$/\1/i')
        fi
done <<< "$HTTP_REQ"

RISKCONTEXT=$(urlencode "{\"b0\":53295,\"b1\":[104,68,180,220],\"b2\":6,\"b3\":[],\"b4\":6,\"b5\":1,\"b6\":\"${USERAGENT}\",\"b7\":[],\"b8\":\"${TIME}:
00\",\"b9\":-120,\"b10\":{\"state\":\"prompt\"},\"b11\":false,\"b12\":{\"charging\":true,\"chargingTime\":0,\"dischargingTime\":null,\"level\":1},\"b13
\":[null,\"1024|728|24\",false,true]}")

HTTP_REQ=$(curl -s -D - -A "${USERAGENT}" -X POST "https://login-ra.fiat.com/accounts.login" -d "loginID=${LOGIN}&password=${PASSWORD}&sessionExpiratio
n=2628000&targetEnv=jssdk&include=profile%2Cdata%2Cemails%2Csubscriptions%2Cpreferences%2C&includeUserInfo=true&loginMode=standard&lang=fr&riskContext=
${RISKCONTEXT}&APIKey=${APIKEY}&source=showScreenSet&sdk=js_latest&authMode=cookie&pageURL=https%3A%2F%2Flogin-ra.fiat.com%2F&sdkBuild=16506&format=jso
n" -H "Cookie: ${GMID} ${UCID} ${HASGMID} ")
while IFS= read -r header
do
        if [[ $header == *"glt_"* ]]; then
                GLT=$(echo $header | sed 's/^Set-Cookie: \([^;]*;\).*$/\1/i')
                LOGIN_TOKEN=$(echo $header | sed 's/^Set-Cookie: [^=]*=\([^;]*\);.*$/\1/i')
        fi
done <<< "$HTTP_REQ"

if [[ $LOGIN_TOKEN == "" ]]; then
        echo "Login ERROR"
        exit 1
fi

HTTP_REQ=$(curl -s -A "${USERAGENT}" -X GET "https://login-ra.fiat.com/saml/v2.0/${APIKEY}/idp/sso/continue?samlContext=${SAMLCONTEXT}&loginToken=${LOG
IN_TOKEN}" -H "Cookie: ${GMID} ${UCID} ${HASGMID} ")
while IFS= read -r data
do
        if [[ $data == *"SAMLResponse"* ]]; then
                SAMLRESPONSE=$(echo $data | sed 's/.* name="SAMLResponse" value="\([^"]*\).*$/\1/i')
                SAMLRESPONSE_ENCODED=$(urlencode $SAMLRESPONSE)
                SERVICEBOX_URL=$(echo $data | sed 's/.* method="post" action="\([^"]*\).*$/\1/i')
        fi
done <<< "$HTTP_REQ"

HTTP_REQ=$(curl -s -D - -A "${USERAGENT}" -X POST "${SERVICEBOX_URL}" -d "SAMLResponse=${SAMLRESPONSE_ENCODED}" -H "Cookie: ${JSESSIONID} ${PSACOUNTRY} ${BIGIPSERVER} ")

echo "${JSESSIONID} ${PSACOUNTRY} ${BIGIPSERVER} "
